### ISSUE TITLE
Exiting - No SRS found

### ISSUE THREAD

**Issue by wussup** [galbiston/geosparql-fuseki#3]
Hello,

I always have the message:
**GeoSPARQL Server:  Exiting - No SRS found. Check 'http://www.opengis.net/ont/geosparql#hasSerialisation' or 'http://www.w3.org/2003/01/geo/wgs84_pos#lat'/'http://www.w3.org/2003/01/geo/wgs84_pos#lon' predicates are present in the source data. Hint: Inferencing with GeoSPARQL schema may be required.: offer**
I am starting the server with arguments _geosparql-fuseki -t offer -d offer_. I would like to start the server with an empty dataset and then fill it with Java code.
Apache SIS is installed and SIS_DATA is set.
_sis crs EPSG:4326_ is executed.

What am I doing wrong?

**Comment by galbiston** [comment]
Hello,

Sorry for the delay in responding. Seems there might have been an oversight in starting from an empty graph. Will look into this case.

However, if you want to add data using Java code then you probably need to use the [Java API](https://github.com/galbiston/geosparql-jena). This project is for sending SPARQL over HTTP to the server. It would require having the `-u` option set to allow updates.

Both of these projects are now available directly in Apache Jena since 3.12.0.

Thanks.

**Comment by wussup** [comment]
> Hello,
> 
> Sorry for the delay in responding. Seems there might have been an oversight in starting from an empty graph. Will look into this case.
> 
> However, if you want to add data using Java code then you probably need to use the [Java API](https://github.com/galbiston/geosparql-jena). This project is for sending SPARQL over HTTP to the server. It would require having the `-u` option set to allow updates.
> 
> Both of these projects are now available directly in Apache Jena since 3.12.0.
> 
> Thanks.

Ok, -u option is useful, but I don't want start SPARQL HTTP server from Java API, I would like to have a standalone server and run it as Docker container and it can be empty on start.

**Comment by galbiston** [comment]
Version 1.1.2 now allows an empty dataset. Please see the note about the GeoSPARQL schema on the README.md.

**Comment by wussup** [comment]
Thank you for the new release, but I still have one more important warning:

> WARN  Datset empty. Spatial Index not constructed. Server will require restarting after adding data and any updates to build Spatial Index.

How I can avoid server restarting after adding data?

**Comment by galbiston** [comment]
The server will not restart after adding data. A restart is required to build a Spatial Index if one is required.

**Comment by wussup** [comment]
My data is spatial and dynamically changing, I'm updating (clear database and adding new data) TDB database with new spatial data every 15 minutes. In that case, am I need to restart the server every 15 minutes?

**Comment by galbiston** [comment]
The restart is only required to build a Spatial Index. The Spatial Index is used to speed up querying and is not required for spatial querying. There are other indexes that can be setup to dynamically improve querying.

**Comment by wussup** [comment]
@galbiston Ok, now I'm understanding. Thank you for the explanation.
