### ISSUE TITLE
How to find the Polygons Intersection inside Apache Fuseki Server?

### ISSUE THREAD

**Issue by manojmsrit** [galbiston/geosparql-fuseki#4]
I am using Apache Jena Fuseki Server for Storing Geo Coordinates of location. How to find out that if two polygons or two rectangles intersect each other inside Fuseki. Please share links related to it if possible. Thank you.

**Comment by galbiston** [comment]
Annex B of the [GeoSPARQL standard](https://portal.ogc.org/files/?artifact_id=47664) provides example queries.
